### ISSUE TITLE
2022 TODO

### ISSUE THREAD

**Issue by kowoo0** [kodooui/sketch-note#3]
- [x] [gatsby](https://www.inflearn.com/course/gatsby-%EA%B8%B0%EC%88%A0%EB%B8%94%EB%A1%9C%EA%B7%B8/dashboard) 강의 학습하고 나만의 블로그 만들기 (진행중)
- [x] [만들고 비교하며 학습하는 React](https://www.inflearn.com/course/%EB%A7%8C%EB%93%A4%EB%A9%B4%EC%84%9C-%ED%95%99%EC%8A%B5%ED%95%98%EB%8A%94-%EB%A6%AC%EC%95%A1%ED%8A%B8/dashboard) 강의 학습
- [ ] [프론트엔드 개발환경의 이해와 실습](https://www.inflearn.com/course/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C-%EA%B0%9C%EB%B0%9C%ED%99%98%EA%B2%BD/dashboard) 강의 학습 (진행중)
- [x] [만들어보며 이해하는 React & Redux](https://fastcampus.co.kr/category_academy_kmt) 강의 학습
- [x] 타입스크립트 스터디 완주 (진행중)
- [ ] 개설한 블로그에 첫 아티클 등록

**Comment by kowoo0** [comment]
실패한 Todo 2023 Todo로 이동
